version: "3"
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    tmpfs:
      - /var/lib/mysql
    volumes:
      - "./files/etc/mysql/my.cnf:/etc/mysql/my.cnf"
      - "./scripts/db:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_DATABASE: redmine
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password